apiVersion: v1
kind: Pod
metadata:
  name: debugpod
spec:
  containers:
  - name: debugpod
    image: voronenko/debug-pod:latest
    command:
      - tail
      - "-f"
      - "/dev/null"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always

